channels:
- conda-forge
- bioconda
dependencies:
- bioconda::sracha=0.3.10
- bioconda::fastp=1.3.3
- bioconda::deacon=0.13.2
- bioconda::mvirs=1.1.1
- bioconda::kmer-db=2.3.1
- bioconda::lz-ani=1.2.3
- conda-forge::csvtk=0.37.0
- bioconda::seqkit=2.13.0
- conda-forge::gzip=1.14
- bioconda::vrhyme=1.1.0
