channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::numpy=2.4.3
- conda-forge::pandas=3.0.2
- conda-forge::polars=1.40.0
- conda-forge::pyarrow=24.0.0
- conda-forge::scikit-learn=1.5.1
- conda-forge::joblib=1.5.3
